# This workflow will setup the .NET version and actions of other workflows

name: Setup .NET
runs:
  using: "composite"
  steps:
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 8.0.x
