# This workflow will attach the executable to the Github release

name: Attach to release

on: 
  release:
    types: [ published ]

jobs:
  attach:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup_dotnet
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Create executable
      run: dotnet publish
      
    - name: Attach executable to release
      run: gh release upload $GITHUB_REF_NAME $ASSET_PATH --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ASSET_PATH: ${{ github.workspace }}/bin/Release/net*-windows/win-x64/publish/ACUWL.exe